# Generated by Django 3.2.19 on 2023-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20230822_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='distance',
            field=models.PositiveIntegerField(default=500, verbose_name='distance'),
        ),
    ]
